# REFRENCE:
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# https://alacritty.org/config-alacritty.html 

import = [
#"~/.config/alacritty/themes/themes/aura.toml"
#"~/.config/alacritty/themes/themes/ayu_dark.toml"
#"~/.config/alacritty/themes/themes/blood_moon.toml"
#"~/.config/alacritty/themes/themes/campbell.toml"
#"~/.config/alacritty/themes/themes/gnome_terminal.toml"

#"~/.config/alacritty/themes/themes/gotham.toml" ## Next
#"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
#"~/.config/alacritty/themes/themes/hyper.toml"
"~/.config/alacritty/themes/themes/iterm.toml"
#"~/.config/alacritty/themes/themes/monokai_charcoal.toml"
#"~/.config/alacritty/themes/themes/seashells.toml"
#"~/.config/alacritty/themes/themes/yebt-0xide.toml"

]
working_directory="None"
live_config_reload=true

[shell]
program="/bin/zsh"
args=["--login"]

[env]
WALO="UWU"
# term="xterm-256color"
# TERM="xterm-256color"
# TERM="screen-256color"
TERM="tmux-256color"


[window]
# padding.x=2
# padding.y=2
padding = { x = 8, y = 4 }
dynamic_padding = true
# decorations = "Full" # Full, None, Transparent, Buttons
decorations = "None" # Full, None, Transparent, Buttons
#dynamic_title = true
#opacity=0.7
#blur=true
#title = "Alacritty"

[font]
# Nice icons
# normal = { family = "Mononoki Nerd Font"} ## Nice, fix reading
# normal = { family = "GohuFont 14 Nerd Font"} ## BETTER
# normal = { family = "Iosevka Nerd Font"}
normal = { family = "BlexMono Nerd Font"}
# normal = { family = "Terminess Nerd Font"} ## 
# normal = { family = "BigBlueTerm437 Nerd Font"}
# normal = { family = "BigBlueTermPlus Nerd Font"}
# normal = { family = "Cascadia Code"}
# normal = { family = "GohuFont 11 Nerd Font"} # NICE
# normal = { family = "iMWritingMono Nerd Font"} 

# normal = { family = "JetBrainsMono Nerd Font"}
# normal = { family = "JetBrains Mono"}
# normal = { family = "Lekton Nerd Font"} ## Little 
# normal = { family = "Fira Mono"} ## 
# normal = { family = "FiraCode Nerd Font"} ## 
# Nice 
# normal = { family = "3270 Nerd Font"}
# normal = { family = "Agave Nerd Font"}

# normal = { family = "AnonymicePro Nerd Font"}
# normal = { family = "Iosevka Nerd Font Mono" }
# normal = { family = "Iosevka NerdFont" }
# normal = { family = "FiraCode NerdFont Mono" }
# normal = { family = "Iosevka" }
# normal = { family = "Iosevka Term", style = "Regular" }
# normal = { family = "Iosevka Fixed", style = "Regular" } # make a better icons
# normal = { family = "BlexMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrains Mono"}
# normal = { family = "Fira Mono"}
# normal = { family = "Cascadia Code"}

#normal = { family = "BigBlueTerm437 Nerd Font", style = "Regular" }
#normal = { family = "BigBlueTerm437 Nerd Font"}
#normal = { family = "3270 Nerd Font"}
#normal = { family = "Agave Nerd Font"}
#normal = { family = "BitstromWera Nerd Font"}
#bold = { family = "Fira Mono", style = "Bold" }

# bold = { style = "Bold" }
# italic = { family = "Victor Mono", style = "Italic" }
# italic = { family = "Iosevka", style="Italic"}
# bold_italic = { family = "BlexMono Nerd Font", style = "Bold Italic" }
# size=11.5
# size=12

[mouse]
hide_when_typing = true

[keyboard]
# bindings = [{ <key>, <mods>, <mode>, <action> | <chars> },]
bindings = [
{ key = "N", mods = "Control | Shift", action = "SpawnNewInstance"  },
#{ key = "M", mods = "Control | Shift", action = "CreateNewWindow"  },
]

# [font.normal]
# # {
# #family = "GT America Mono"
# #family = "Agave Nerd Font"
# #family = "FiraCode Nerd Font"
# #family = "BlexMono Nerd Font"
# #family = "Geist Mono"
# #family = "Fira Mono"
# #family = "BigBlueTerm437 Nerd Font"
# #family = "Iosevka Nerd Font"
# #family = "CaskaydiaCove Nerd Font"
# #family = "GohuFont 11 Nerd Font" ##
# #family = "GohuFont 14 Nerd Font"
# #family = "Hack Nerd Font Mono"
# #family = "iMWritingMono Nerd Font"
# #family = "iMWritingMono Nerd Font Mono" ##
# #family = "Inconsolata LGC Nerd Font Mono"
# #family = "InconsolataGo Nerd Font Mono"
# family = "Iosevka Nerd Font Mono" ### --
# #family = "JetBrains Mono" ##
# #family = "Liberation Mono"  ##
# #ly = "M+1Code Nerd Font"  ###
# #family = "SauceCodePro Nerd Font" 
# #family = "UbuntuMono Nerd Font" 
# #family = "Victormono Nerd Font"  ##
# #  
# #  
# # [keyboard]
# # bindings = [{ <key>, <mods>, <mode>, <action> | <chars> },]
