import = ["/home/eb/.config/alacritty/themes/iterm.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Agave Nerd Font"

[window]
dynamic_padding = true
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 2
y = 2
