#import = ["/home/eb/.config/alacritty/themes/iterm.toml"]
#import = ["~/.config/alacritty/themes/yebt-0xide.toml"]
import = [
    "~/.config/alacritty/themes/themes/yebt-0xide.toml"
]

live_config_reload = true


# [shell]
# program="/bin/zsh"
# args=["--login"]
#[shell]
# program="/bin/fish"
# args=["--login"]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "GT America mono"
#family = "Agave Nerd Font"

[window]
dynamic_padding = true
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 2
y = 2

