splash=false
wallpaper {
    monitor = 
    #path = ~/Pictures/wallpapers/wallhaven-5ymlv9.png
    path = ~/Pictures/wallpapers/
    #path = ~/Pictures/wallpapers/
    fit_mode = cover

}

#preload = ~/Pictures/wallpapers/wallhaven-3q6kjv.png
# wallpaper {
#     monitor = 
#     path = ~/fallback.jxl
#     fit_mode = cover
# }
